### ISSUE TITLE
Let crc-usage show all users

### ISSUE THREAD

**Issue by chnixi** [pitt-crc/bank#334]
In the past, crc-usage was able to display all users of an account, as described in the SOP for user creation: 
github.com/pitt-crc/SOP/tree/main/user_account_management/user_account_creation.md. 

Would it be possible to restore this again?

**Comment by Comeani** [comment]
Recent discussion favored setting up a wrapper to display SLURM account association and possibly user group membership instead of trying to show everyone in the `crc-bank account info` output (used in `crc-usage`).
